# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXProjectFramework' do

pod 'ReactiveCocoa', '2.4.7'
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'MJExtension', '~> 3.0.13'



end
